name: "Google Cloud SQL Proxy"
description: "Start Google CloudSQL Proxy"

branding:
  icon: "database"
  color: "red"

inputs:
  creds:
    description: "Contents of a Service Account JSON Key"
    required: true
  instance:
    description: "CloudSQL instance"
    required: true
  port:
    description: "Listen on port"
    required: false
    default: 5432
  proxy_version:
    description: "CloudSQL Proxy Version"
    required: false
    default: 1.21.0

runs:
  using: "composite"
  steps:
    - name: Prepare Google Cloud SQL Proxy Credentials
      shell: bash
      run: |
        # Create directory in GITHUB_WORKSPACE
        mkdir -p $GITHUB_WORKSPACE/gce-cloudsql-proxy
        echo '${{ inputs.creds }}' > $GITHUB_WORKSPACE/gce-cloudsql-proxy/key.json
        chmod 600 $GITHUB_WORKSPACE/gce-cloudsql-proxy/key.json

    - name: Start Google Cloud SQL Proxy
      shell: bash
      run: |
        # Start container with the mounted GITHUB_WORKSPACE path
        docker run -d --net host --name gce-cloudsql-proxy --restart on-failure \
        -v $GITHUB_WORKSPACE/gce-cloudsql-proxy:/cloudsql-creds \
        gcr.io/cloudsql-docker/gce-proxy:${{ inputs.proxy_version }} \
        /cloud_sql_proxy \
          -credential_file /cloudsql-creds/key.json \
          -dir /cloudsql-creds \
          -instances=${{ inputs.instance }}=tcp:127.0.0.1:${{ inputs.port }}

        # Wait until connections are accepted
        sleep 3
        isready=0
        for i in {1..10}; do
          echo "Wait for connections to be ready ... $i/10"
          (${{ github.action_path }}/wait-for-it.sh --quiet --timeout=3 --host=127.0.0.1 --port=${{ inputs.port }} || exit $?) && true
          isready=$?
          if [[ $isready -eq 0 ]]; then
            break
          fi
          sleep 2
        done

        # Print container logs
        docker logs gce-cloudsql-proxy

        # Exit with error code if we couldn't connect
        if [[ $isready -ne 0 ]]; then
          exit $isready 
        fi